version: ~> 1.0
language: node_js
node_js:
  - '12'

before_script:
  - npm install -g gatsby-cli  
script:
  - "npm run test"
  - "npm run build"
cache:
  directories:
    - public
    - node_modules
    - .cache
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: main    